export default {
    INVALID_USER: "INVALID_USER",
    PASSWORD_ERROR: "PASSWORD_ERROR",
    USER_NO_NAMESPACE: "USER_NO_NAMESPACE",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    NAMESPACE_DISABLED: "NAMESPACE_DISABLED",
    NAMESPACE_DENIED: "NAMESPACE_DENIED",
    SESSION_EXPIRED: "SESSION_EXPIRED",
    SUPPORT_MD5: "SUPPORT_MD5"
}